version: "3.5"
services:
  db:
    container_name: postgres11.2-alpine-database
    build:
      context: .setup
      dockerfile: ../db.Dockerfile
    # image: postgres:11.2-alpine
    restart: unless-stopped
    hostname: db
    networks:
      - vapor-it
    #ports:
    #  - 5432:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_HOST: db
      POSTGRES_DB: test
      POSTGRES_PORT: 5432
      PGDATA: /var/lib/postgresql/data
    volumes:
      - database_data:/var/lib/postgresql/data
    #command: ["./docker-entrypoint.sh", "db:5432", "postgres"]

  api:
    container_name: vapor_it_container
    hostname: api
    build:
      context: .
      dockerfile: dev.Dockerfile
    image: api:dev
    networks:
      - vapor-it
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_HOST: db
      POSTGRES_DB: test
      POSTGRES_PORT: 5432
    ports:
      - 5000
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
    entrypoint: bash
    restart: always
    depends_on:
      - db


  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    hostname: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: mwhelan@parkenergyservices.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - vapor-it
    restart: unless-stopped
    depends_on:
      - db

networks:
  vapor-it:
    driver: bridge

volumes:
  database_data:
    driver: local
    driver_opts:
      type: none
      device: $HOME/docker/volumes/vapor_postgres
      o: bind
  pgadmin:

