version: "3.5"
services:
  db:
    container_name: postgres11.2-alpine-database
    #build:
    #  context: .setup
    #  dockerfile: ../db.Dockerfile
    image: postgres:11.2-alpine
    restart: always
    hostname: db
    networks:
      vapor-it:
        ipv4_address: 192.168.48.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - $HOME/docker/volumes/vapor_postgres/:/var/lib/postgresql/data
    #command: ["./docker-entrypoint.sh", "db:5432", "postgres"]

  api:
    container_name: vapor_it_container
    hostname: api
    build:
      context: .
      dockerfile: dev.Dockerfile
    image: api:dev
    networks:
      - vapor-it
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
      POSTGRES_PORT: 5432
    ports:
      - 8080:8080
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
    entrypoint: bash
    restart: always
    depends_on:
      - db

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    hostname: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: test
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - 4000:80
    networks:
      - vapor-it
    restart: unless-stopped
    depends_on:
      - db

networks:
  vapor-it:
    ipam:
      driver: default
      config:
        - subnet: 192.168.48.0/20

volumes:
  database_data:
    driver: local
  pgadmin:

