version: 2

jobs:
  build:
    docker:
      - image: codevapor/swift:5.0
        environment:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
          DB_HOSTNAME: db
          PORT: 5432
      - image: circleci/postgres:11.2-alpine-postgis-ram
        name: db
        environment:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get install -yq libssl-dev pkg-config
      - run: swift build
      - run: swift test

  push-to-docker-hub:
    docker:
      - image: docker:latest
    steps:
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --update --no-cache curl jq python py-pip
      - run:
          name: Build Docker Image
          command: |
            docker build -t api .
            docker tag api mjwrazor/swiftdevopsrepo:latest
            docker tag api mjwrazor/swiftdevopsrepo:$CIRCLE_SHA1
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push mjwrazor/swiftdevopsrepo:latest
            docker push mjwrazor/swiftdevopsrepo:$CIRCLE_SHA1
workflows:
  version: 2
  tests:
    jobs:
      - build
      - push-to-docker-hub:
          requires:
            - build
          context: dockerhub
          filters:
            branches:
              only: master