version: 2.0

references:
  workspace_root: &workspace_root
    /tmp/workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

jobs:
  build-image:
    working_directory: /root/backend
    docker:
      - image: norionomura/swift:5.0
        environment:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
          DB_HOSTNAME: db
          PORT: 5432
      - image: circleci/postgres:11.2-alpine-postgis-ram
        name: db
        environment:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get install -yq libssl-dev pkg-config
      - run: swift build
      - run: swift test
      - run:
          name: Save build
          command: |
            pwd
            ls -al
      - persist_to_workspace:
          root: .
          paths:
            - .
  push-to-docker-hub:
    docker:
      - image: docker:latest
        environment:
          IMAGE_TAG: ci-testing-image
    working_directory: /root/backend
    steps:
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --update --no-cache curl jq python py-pip
      - *attach_workspace
      - run:
          name: Move build to deploy
          command: |
            mv /tmp/workspace .
      - run:
          name: Build Docker Image
          command: |
            cd workspace
            pwd
            ls -al
            docker build -t api .
            docker tag api mjwrazor/swiftdevopsrepo:latest
            docker tag api mjwrazor/swiftdevopsrepo:$CIRCLE_SHA1
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push mjwrazor/swiftdevopsrepo:latest
            docker push mjwrazor/swiftdevopsrepo:$CIRCLE_SHA1
workflows:
  version: 2
  build_and_test:
    jobs:
      - build-image
  push_to_hub:
    jobs:
      - build-image
      - push-to-docker-hub:
          requires:
            - build-image
          filters:
            branches:
              only: master